# To create an encoded user:password pair, the following command can be used:
# htpasswd -nb user password | base64

apiVersion: v1
kind: Secret
metadata:
  name: kube-explorer
  namespace: kube-system
  labels:
    app: kube-explorer
data:
  auth: bml1c21hbGxuYW46JGFwcjEkbDdUZjJOdWskbmNXajYubHYvMGNkcXM0NFoyelVQLgoK
type: Opaque
