# The definitions below require the definitions for the Middleware and IngressRoute kinds.
# https://doc.traefik.io/traefik/reference/dynamic-configuration/kubernetes-crd/#definitions
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: kube-explorer
  namespace: kube-system
  labels:
    app: kube-explorer
spec:
  basicAuth:
    secret: kube-explorer
    removeHeader: true

---
# To create an encoded user:password pair, the following command can be used:
# htpasswd -nb user password | base64

apiVersion: v1
kind: Secret
metadata:
  name: kube-explorer
  namespace: kube-system
  labels:
    app: kube-explorer
data:
  auth: bml1c21hbGxuYW46JGFwcjEkbDdUZjJOdWskbmNXajYubHYvMGNkcXM0NFoyelVQLgoK
type: Opaque
