apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-explorer
  namespace: kube-system
  labels:
    app: kube-explorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-explorer
  template:
    metadata:
      namespace: kube-system
      labels:
        app: kube-explorer
    spec:
      serviceAccountName: kube-explorer
      containers:
      - image: niusmallnan/kube-explorer
        imagePullPolicy: IfNotPresent
        name: kube-explorer
        ports:
        - containerPort: 8989
          protocol: TCP
        args:
        - "--https-listen-port=0"
        - "--http-listen-port=8989"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-explorer-shell
  namespace: kube-system
  labels:
    app: kube-explorer-shell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-explorer-shell
  template:
    metadata:
      namespace: kube-system
      labels:
        app: kube-explorer-shell
    spec:
      serviceAccountName: kube-explorer
      containers:
      - image: rancher/shell:v0.1.6
        imagePullPolicy: IfNotPresent
        name: shell
        stdin: true
        tty: true
        securityContext:
          runAsUser: 0
