apiVersion: v1
kind: Service
metadata:
  name: kube-explorer
  namespace: kube-system
  labels:
    app: kube-explorer
spec:
  type: NodePort
  ports:
  - port: 8989
    targetPort: 8989
    protocol: TCP
    name: http
    nodePort: 30089
  selector:
    app: kube-explorer

